[package]
name = "slack-test"
version = "0.1.0"
authors = ["Seungmin Lee <elenesgu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack = "0.22.0"
serde_json = "1.0"
